OTBSCore/Controllers/LogOutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OTBSCore.Models;

namespace OTBSCore.Controllers
{
    public class LogOutController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public LogOutController(SignInManager<ApplicationUser> signInManager,UserManager<ApplicationUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            
            await _signInManager.SignOutAsync();
            ICollection<string> roleNames =await  _userManager.GetRolesAsync(await _userManager.FindByIdAsync( _userManager.GetUserId(HttpContext.User)));
            var roleName = roleNames.FirstOrDefault();


            if (roleName == "Admin")
                return RedirectToAction("Index", "Admin");

            if (roleName == "Committee")
                return RedirectToAction("Index", "Committee");

            if (roleName == "Counter")
                return RedirectToAction("Index", "Counter");

            return View("Error");
        }
    }
}

OTBSCore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>@ViewData["Title"] - Book Tickets Online</title>

    <!-- Custom fonts for this template-->
    <link
      href="~/sb-admin/vendor/fontawesome-free/css/all.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="~/sb-admin/css/sb-admin-2.min.css" rel="stylesheet" />
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        @if (ViewData["roleName"].ToString() == "Counter")
          {
            <a
            class="sidebar-brand d-flex align-items-center justify-content-center"
            href="/counterloggedin">
            <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-bus"></i>
            </div>
            <div class="sidebar-brand-text mx-3">OTBS<sup>Counter</sup></div>
            </a>
          }
          else if (ViewData["roleName"].ToString() == "Committee")
          {
           <a
            class="sidebar-brand d-flex align-items-center justify-content-center"
            href="/committeeloggedin">
            <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-bus"></i>
            </div>
            <div class="sidebar-brand-text mx-3">OTBS<sup>Committee</sup></div>
            </a>
          }
          else
          {
           <a
            class="sidebar-brand d-flex align-items-center justify-content-center"
            href="/loggedin">
            <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-bus"></i>
            </div>
            <div class="sidebar-brand-text mx-3">OTBS<sup>Admin</sup></div>
            </a>
          }

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

          @if (ViewData["roleName"].ToString() == "Counter")
          {
             @await Html.PartialAsync("_CounterSidebar")
          } else if (ViewData["roleName"].ToString() == "Committee")
          {
             @await Html.PartialAsync("_CommitteeSidebar")
          } else
          {
            @await Html.PartialAsync("_AdminSidebar")
          }

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - User Information -->
              @await Html.PartialAsync("_CommonLoginLayout")
            </ul>
          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!-- <partial name="_CookieConsentPartial" /> -->
            <main role="main" class="pb-3">
              @RenderBody()
            </main>
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Online Ticket Booking</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <form asp-action="Index" asp-controller="LogOut">
              <input type="submit" value="Logout" class="btn btn-primary" />
            </form>
            <!-- <a class="btn btn-primary" href="login.html">Logout</a> -->
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery/jquery.min.js"
      asp-append-version="true"
    ></script>
    <script
      src="~/sb-admin/vendor/bootstrap/js/bootstrap.bundle.min.js"
      asp-append-version="true"
    ></script>

    <!-- Core plugin JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery-easing/jquery.easing.min.js"
      asp-append-version="true"
    ></script>

    <!-- Custom scripts for all pages-->
    <script src="~/sb-admin/js/sb-admin-2.min.js"></script>

    @RenderSection("Scripts", required: false)
  </body>
</html>

OTBSCore/Views/Shared/_AdminSidebar.cshtml
<!-- Nav Item - Dashboard -->
<li class="nav-item">
    <a class="nav-link" href="/loggedin">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span>
    </a>
</li>

<!-- Nav Item - Destination -->
<li class="nav-item">
    <a class="nav-link" href="/destination">
        <i class="fas fa-fw fa-map-marker-alt"></i>
        <span>Destination</span>
    </a>
</li>

<!-- Nav Item - RouteAndFare -->
<li class="nav-item">
    <a class="nav-link" href="/routeandfare">
        <i class="fas fa-fw fa-map-marked-alt"></i>
        <span>Route And Fare</span>
    </a>
</li>

<!-- Nav Item - Schedule -->
<li class="nav-item">
    <a class="nav-link" href="/schedule">
        <i class="fas fa-fw fa-hourglass-end"></i>
        <span>Schedule</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="/client/viewclientlist">
        <i class="fas fa-fw fa-users"></i>
        <span>Customer Details</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="/admin/viewcommitteelist">
        <i class="fas fa-fw fa-layer-group"></i>
        <span>Committee List</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="/counter/viewcounterlist">
        <i class="fas fa-fw fa-store"></i>
        <span>Counter List</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="/committeedue">
        <i class="fas fa-fw fa-money-bill-wave"></i>
        <span>Committee Due</span>
    </a>
</li>

<li class="nav-item">
    <a class="nav-link" href="/customerdue">
        <i class="fas fa-fw fa-shopping-basket"></i>
        <span>Customer Due</span>
    </a>
</li>

OTBSCore/Views/Shared/_CommitteeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>@ViewData["Title"] - Book Tickets Online</title>

    <!-- Custom fonts for this template-->
    <link
      href="~/sb-admin/vendor/fontawesome-free/css/all.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="~/sb-admin/css/sb-admin-2.min.css" rel="stylesheet" />
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="/committeeloggedin"
        >
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-bus"></i>
          </div>
          @if (ViewData["roleName"] == "Committee")
          {
            <div class="sidebar-brand-text mx-3">OTBS<sup>Committee</sup></div>
          }
          else
          {
            <div class="sidebar-brand-text mx-3">OTBS<sup>Admin</sup></div>
          }
          
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
          <a class="nav-link" href="/committeeloggedin">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>

        <!-- Nav Item - Destination -->
        <li class="nav-item">
          <a class="nav-link" href="/vehicledata">
            <i class="fas fa-fw fa-bus"></i>
            <span>Vehicle</span></a
          >
        </li>

        <!-- Nav Item - Schedule -->
        <li class="nav-item">
          <a class="nav-link" href="/schedule">
            <i class="fas fa-fw fa-hourglass-end"></i>
            <span>Schedule</span></a
          >
        </li>

        <!-- Nav Item - View Client List -->
        <li class="nav-item">
          <a class="nav-link" href="/client/viewclientlist">
            <i class="fas fa-fw fa-users"></i>
            <span>Customer Details</span></a
          >
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/counter/viewcounterlist">
            <i class="fas fa-fw fa-building"></i>
            <span>Counter Details</span></a
          >
        </li>



        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - User Information -->
              @await Html.PartialAsync("_CommonLoginLayout")
            </ul>
          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!-- <partial name="_CookieConsentPartial" /> -->
            <main role="main" class="pb-3">
              @RenderBody()
            </main>
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Online Ticket Booking</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <form asp-action="Index" asp-controller="LogOut">
              <input type="submit" value="Logout" class="btn btn-primary" />
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery/jquery.min.js"
      asp-append-version="true"
    ></script>
    <script
      src="~/sb-admin/vendor/bootstrap/js/bootstrap.bundle.min.js"
      asp-append-version="true"
    ></script>

    <!-- Core plugin JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery-easing/jquery.easing.min.js"
      asp-append-version="true"
    ></script>

    <!-- Custom scripts for all pages-->
    <script src="~/sb-admin/js/sb-admin-2.min.js"></script>

    @RenderSection("Scripts", required: false)
  </body>
</html>

OTBSCore/Views/Shared/_CommitteeSidebar.cshtml
<!-- Nav Item - Dashboard -->
<li class="nav-item">
  <a class="nav-link" href="/committeeloggedin">
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>Dashboard</span></a
  >
</li>

<!-- Nav Item - Destination -->
<li class="nav-item">
  <a class="nav-link" href="/vehicledata">
    <i class="fas fa-fw fa-bus"></i>
    <span>Vehicle</span></a
  >
</li>

<!-- Nav Item - Schedule -->
<li class="nav-item">
  <a class="nav-link" href="/schedule">
    <i class="fas fa-fw fa-hourglass-end"></i>
    <span>Schedule</span></a
  >
</li>

<!-- Nav Item - View Client List -->
<li class="nav-item">
  <a class="nav-link" href="/client/viewclientlist">
    <i class="fas fa-fw fa-users"></i>
    <span>Customer Details</span></a
  >
</li>

<li class="nav-item">
  <a class="nav-link" href="/counter/viewcounterlist">
    <i class="fas fa-fw fa-building"></i>
    <span>Counter Details</span></a
  >
</li>

<li class="nav-item">
  <a class="nav-link" href="/vehiclecustomer">
    <i class="fas fa-fw fa-user-tie"></i>
    <span>Print customer List</span></a
  >
</li>

OTBSCore/Views/Shared/_CommonLoginLayout.cshtml
@using Microsoft.AspNetCore.Identity 
@inject UserManager<ApplicationUser> UserManager 
@inject SignInManager<ApplicationUser> SignInManager 
	@if (SignInManager.IsSignedIn(User)) {

    <li class="nav-item">
      <a
        class="nav-link"
        href="#logoutModal"
        id="userDropdown"
        role="button"
        data-toggle="modal"
        aria-haspopup="true"
        aria-expanded="false"
	  >
	  @{
		var user = await UserManager.FindByNameAsync(UserManager.GetUserName(User));
		ICollection<string> roleNames = await UserManager.GetRolesAsync(user);

	}
        <span class="mr-2 d-lg-inline text-gray-700">
				@user.UserName
		</span>
      </a>
    </li>

    }
  </ApplicationUser></ApplicationUser
>

OTBSCore/Views/Shared/_CounterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>@ViewData["Title"] - Book Tickets Online</title>

    <!-- Custom fonts for this template-->
    <link
      href="~/sb-admin/vendor/fontawesome-free/css/all.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="~/sb-admin/css/sb-admin-2.min.css" rel="stylesheet" />
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="/loggedin"
        >
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-bus"></i>
          </div>
          <div class="sidebar-brand-text mx-3">OTBS<sup>Counter</sup></div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0" />

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
          <a class="nav-link" href="loggedin">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>

        <!-- Nav Item - Destination -->
        <li class="nav-item">
          <a class="nav-link" href="/destination">
            <i class="fas fa-fw fa-map-marker-alt"></i>
            <span>Destination</span></a
          >
        </li>

        <!-- Nav Item - RouteAndFare -->
        <li class="nav-item">
          <a class="nav-link" href="/routeandfare">
            <i class="fas fa-fw fa-map-marked-alt"></i>
            <span>Route And Fare</span></a
          >
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block" />

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Nav Item - User Information -->
              @await Html.PartialAsync("_CommonLoginLayout")
            </ul>
          </nav>
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!-- <partial name="_CookieConsentPartial" /> -->
            <main role="main" class="pb-3">
              @RenderBody()
            </main>
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; Online Ticket Booking</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <form asp-action="Index" asp-controller="LogOut">
              <input type="submit" value="Logout" class="btn btn-primary" />
            </form>
            <!-- <a class="btn btn-primary" href="login.html">Logout</a> -->
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery/jquery.min.js"
      asp-append-version="true"
    ></script>
    <script
      src="~/sb-admin/vendor/bootstrap/js/bootstrap.bundle.min.js"
      asp-append-version="true"
    ></script>

    <!-- Core plugin JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery-easing/jquery.easing.min.js"
      asp-append-version="true"
    ></script>

    <!-- Custom scripts for all pages-->
    <script src="~/sb-admin/js/sb-admin-2.min.js"></script>

    @RenderSection("Scripts", required: false)
  </body>
</html>

OTBSCore/Views/Shared/_CounterSidebar.cshtml
<!-- Nav Item - Dashboard -->
<li class="nav-item">
  <a class="nav-link" href="/counterloggedin">
    <i class="fas fa-fw fa-tachometer-alt"></i>
    <span>Dashboard</span></a
  >
</li>

<li class="nav-item">
  <a class="nav-link" href="/counter/bookticket">
    <i class="fas fa-fw fa-ticket-alt"></i>
    <span>Book Ticket</span></a
  >
</li>

<li class="nav-item">
          <a class="nav-link" href="/client/viewclientlist">
            <i class="fas fa-fw fa-users"></i>
            <span>Customer Details</span></a
          >
        </li>

OTBSCore/Views/Shared/_LoginLayout.cshtml
@using Microsoft.AspNetCore.Identity

@inject UserManager<ApplicationUser> UserManager
@inject SignInManager<ApplicationUser> SignInManager



@if (SignInManager.IsSignedIn(User))
{

	<div class="border-right">
		<form asp-action="Index" asp-controller="LogOut">
			<text>hello </text>
			@{
				var user = await UserManager.FindByNameAsync(UserManager.GetUserName(User));
				ICollection<string> roleNames = await UserManager.GetRolesAsync(user);

			}
			<text>@roleNames.FirstOrDefault()</text>



			<text>@user.UserName</text>
			<input type="submit" value="Logout" class="btn btn-primary" />
		</form>

	</div>
	
	
}

OTBSCore/Views/Shared/_LoginRegisterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>@ViewData["Title"] - Book Tickets Online</title>

    <link
      href="~/sb-admin/vendor/fontawesome-free/css/all.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="~/sb-admin/css/sb-admin-2.min.css" rel="stylesheet" />
  </head>

  <body class="bg-gradient-primary">
    @RenderBody()

    <!-- Bootstrap core JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery/jquery.min.js"
      asp-append-version="true"
    ></script>
    <script
      src="~/sb-admin/vendor/bootstrap/js/bootstrap.bundle.min.js"
      asp-append-version="true"
    ></script>

    <!-- Core plugin JavaScript-->
    <script
      src="~/sb-admin/vendor/jquery-easing/jquery.easing.min.js"
      asp-append-version="true"
    ></script>

    <!-- Custom scripts for all pages-->
    <script src="~/sb-admin/js/sb-admin-2.min.js"></script>

    @RenderSection("Scripts", required: false)
  </body>
</html>